/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 7.35.0
 * source: limites.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace limites {
    export class LimiteRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            renda?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("renda" in data && data.renda != undefined) {
                    this.renda = data.renda;
                }
            }
        }
        get renda() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set renda(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            renda?: number;
        }): LimiteRequest {
            const message = new LimiteRequest({});
            if (data.renda != null) {
                message.renda = data.renda;
            }
            return message;
        }
        toObject() {
            const data: {
                renda?: number;
            } = {};
            if (this.renda != null) {
                data.renda = this.renda;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.renda != 0)
                writer.writeDouble(1, this.renda);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LimiteRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LimiteRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.renda = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): LimiteRequest {
            return LimiteRequest.deserialize(bytes);
        }
    }
    export class LimiteResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            valor1?: number;
            valor2?: number;
            valor3?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("valor1" in data && data.valor1 != undefined) {
                    this.valor1 = data.valor1;
                }
                if ("valor2" in data && data.valor2 != undefined) {
                    this.valor2 = data.valor2;
                }
                if ("valor3" in data && data.valor3 != undefined) {
                    this.valor3 = data.valor3;
                }
            }
        }
        get valor1() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set valor1(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get valor2() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set valor2(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get valor3() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set valor3(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            valor1?: number;
            valor2?: number;
            valor3?: number;
        }): LimiteResponse {
            const message = new LimiteResponse({});
            if (data.valor1 != null) {
                message.valor1 = data.valor1;
            }
            if (data.valor2 != null) {
                message.valor2 = data.valor2;
            }
            if (data.valor3 != null) {
                message.valor3 = data.valor3;
            }
            return message;
        }
        toObject() {
            const data: {
                valor1?: number;
                valor2?: number;
                valor3?: number;
            } = {};
            if (this.valor1 != null) {
                data.valor1 = this.valor1;
            }
            if (this.valor2 != null) {
                data.valor2 = this.valor2;
            }
            if (this.valor3 != null) {
                data.valor3 = this.valor3;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.valor1 != 0)
                writer.writeDouble(1, this.valor1);
            if (this.valor2 != 0)
                writer.writeDouble(2, this.valor2);
            if (this.valor3 != 0)
                writer.writeDouble(3, this.valor3);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): LimiteResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new LimiteResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.valor1 = reader.readDouble();
                        break;
                    case 2:
                        message.valor2 = reader.readDouble();
                        break;
                    case 3:
                        message.valor3 = reader.readDouble();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): LimiteResponse {
            return LimiteResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedLimiteServiceService {
        static definition = {
            CalcularTodosLimites: {
                path: "/limites.LimiteService/CalcularTodosLimites",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: LimiteRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => LimiteRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: LimiteResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => LimiteResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract CalcularTodosLimites(call: grpc_1.ServerUnaryCall<LimiteRequest, LimiteResponse>, callback: grpc_1.sendUnaryData<LimiteResponse>): void;
    }
    export class LimiteServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedLimiteServiceService.definition, "LimiteService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        CalcularTodosLimites: GrpcUnaryServiceInterface<LimiteRequest, LimiteResponse> = (message: LimiteRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<LimiteResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<LimiteResponse>, callback?: grpc_1.requestCallback<LimiteResponse>): grpc_1.ClientUnaryCall => {
            return super.CalcularTodosLimites(message, metadata, options, callback);
        };
    }
}
